[package]
name = "tx-sender"
version = "0.1.0"
edition = "2021"

[dependencies]
low-latency-utils = { path = "../low-latency-utils" }
rustls = { version = "0.23", default-features = false, features = ["ring", "std", "tls12"] }
rustls-pki-types = "1"
base64-simd = "0.8"
arrayvec = "0.7"
libc = "0.2"
core_affinity = "0.8"
quinn-proto = { version = "0.11", default-features = false, features = ["rustls-ring"] }
bytes = "1"
rcgen = "0.13"
io-uring = { version = "0.7", optional = true }
crossbeam-channel = "0.5"
webpki-roots = "0.26"

[features]
default = ["registry", "io-uring"]
registry = []
io-uring = ["dep:io-uring"]
libtpa = []

[dev-dependencies]
quinn = { version = "0.11", default-features = false, features = ["rustls-ring", "runtime-tokio"] }
tokio = { version = "1", features = ["rt", "rt-multi-thread", "net", "time", "sync", "macros"] }
